// <auto-generated />
namespace FamilyManagementSoftware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newmigration33 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmigration33));
        
        string IMigrationMetadata.Id
        {
            get { return "201610191426290_newmigration33"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
